# Cloudflare Worker configuration
name = "rpac-openai-api-worker"
main = "src/index.js"
compatibility_date = "2024-01-28"

# Environment variables and secrets
# The OPENAI_API_KEY should be set as a secret using:
# wrangler secret put OPENAI_API_KEY

# Optional: Set up custom domain routing
# routes = [
#   { pattern = "api.yourdomain.com/*", zone_name = "yourdomain.com" }
# ]
